### ISSUE TITLE
Open garrison xml will show "Invalid target type: sys-sys-power8"

### ISSUE THREAD

**Issue by sword-huang** [open-power/common-mrw-xml#16]
I can use Serverwiz 2.2 open garrison-xml file (https://github.com/open-power/garrison-xml).
When I use Serverwiz 2.5 to open the xml file, it show "Invalid target type: sys-sys-power8".

**Comment by nkskjames** [comment]
@ruby452, can you look at this?

**Comment by ruby452** [comment]
@sword-huang , I believe you are pointing to the wrong branch. The master branch will contain P9 information mostly while the P8 documents are in the master-p8 branch. You'll need to be in the master-p8 branch in order to avoid getting the invalid target error. The sys-sys-power8.xml file no longer exists under the master branch it will only exist in the master-p8 branch.

**Comment by sword-huang** [comment]
I just use serverwiz 2.5 to open garrison xml. When I launch serverwiz first time, It downloads the common-mrw-xml from here. Do I download master-p8 branch by myself or I use the wrong serverwiz version?

**Comment by nkskjames** [comment]
That is a bug.  The serverwiz in master-p8 branch should download master-p8 common-mrw-xml.  Do you have a git client on your system you can download branch manually and make sure it is ok?

**Comment by sword-huang** [comment]
If I download master-p8 common-mrw-xml into serverwiz 2.5 to replace the original common-mrw-xml, I can open the garrison xml.
